### ISSUE TITLE
Weights not found in Google Drive?

### ISSUE THREAD

**Issue by Deepanker-rawat** [Jzy2017/TACL#1]
Hi, thanks for your work.
Can you provide the weights for the model?

**Comment by Jzy2017** [comment]
> Hi, thanks for your work. Can you provide the weights for the model?

Thanks for your reminder, we have recovered the model uploaded in google drive.

**Comment by Deepanker-rawat** [comment]
Thank you for providing pre-trained weights. You are doing great work!!
